# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  #config.vm.box = "Centos-7-minimal"
  config.vm.box = "erick0z/centos7-64-puppet"

  # Controller node
  config.vm.define "controller" do |controller_config|
    controller_config.vm.hostname = "controller"
    controller_config.vm.network "private_network", ip: "10.0.0.11"
    config.vm.provision "file", source: "network-config/", destination: "/tmp/"
    controller_config.vm.provision "shell" do |s|
      s.path = "fix-host.sh"
      s.args = "controller"
    end
    controller_config.vm.provider "virtualbox" do |vm|
        #vm.gui = true
        vm.customize ["modifyvm", :id, "--memory", "1024"]
        vm.customize ["modifyvm", :id, "--cpus", "1"]
    end
  end

  # End controller node

 # Compute node
  config.vm.define "compute" do |compute_config|
    compute_config.vm.hostname = "compute"
    compute_config.vm.network "private_network", ip: "10.0.0.31"
    compute_config.vm.network "private_network", ip: "10.0.1.31"
    config.vm.provision "file", source: "network-config/", destination: "/tmp/"
    compute_config.vm.provision "shell" do |s|
      s.path = "fix-host.sh"
      s.args = "compute"
    end
    compute_config.vm.provider "virtualbox" do |vm|
        #vm.gui = true
        vm.customize ["modifyvm", :id, "--memory", "1024"]
        vm.customize ["modifyvm", :id, "--cpus", "1"]
    end
  end
  # End Compute node

  # Network node
  config.vm.define "network" do |network_config|
    network_config.vm.hostname = "network"
    network_config.vm.network "private_network", ip: "10.0.0.21"
    network_config.vm.network "private_network", ip: "10.0.1.21"
    network_config.vm.network "private_network", ip: "10.0.10.21"
    config.vm.provision "file", source: "network-config/", destination: "/tmp/"
    network_config.vm.provision "shell" do |s|
      s.path = "fix-host.sh"
      s.args = "network"
    end
    network_config.vm.provider "virtualbox" do |vm|
      #vm.gui = true
      vm.customize ["modifyvm", :id, "--memory", "512"]
      vm.customize ["modifyvm", :id, "--cpus", "1"]
    end
    # Start Deployment... NOT WORKING, see fix-host.sh
    #config.vm.provision "shell", inline: "ssh root@10.0.0.9 packstack --answerfile=/packstack/ans.txt"
  end
  # End Network node
end
